apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: mosaico
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: acrmosaico.azurecr.io/aks-runner-mosaico-dev:2.0.3  #use our own from acr
        env:
        - name: GITHUB_OWNER
          value: sapiency-io
        - name: GITHUB_REPOSITORY
          value: mosaico-reference
        - name: GITHUB_PAT # stored separately in a Kubernetes Secret
          valueFrom:
            secretKeyRef:
              name: controller-manager
              key: pat
      imagePullSecrets:
        - name: acr-secret

        