name: "Build and push Frontend"
description: "Build frontend and push docker image"

inputs:
  STORAGE_CONTAINER_NAME:
    description: "Storage container name, where we want to upload Core Frontend"
    required: true
  STORAGE_ACCOUNT_NAME:
    description: "storage account name"
    required: true
  APP_VERSION:
    description: "Semver App version"
    required: true
  CONNECTION_STRING:
    description: "Connection string to container where we want to upload"
    required: true
  AZURE_CREDENTIALS:
    description: "Credentials used to authenticate Azure"
    required: true
  AZURE_CLIENT_ID:
    description: "Azure Client ID (same from dev.tfvars)"
    required: true 
  AZURE_CLIENT_SECRET:
    description: "Azure Client Secret (same from dev.tfvars)"
    required: true
  AZURE_TENANT_ID:
    description: "Azure Tenant ID (same from dev.tfvars)"
    required: true 
runs:
  using: "composite"
  steps:
    
    - run: az --version
      shell: bash
    - run: ls -la
      shell: bash
    - name: login to az
      shell: bash
      run: |
        az login --service-principal -u ${{ inputs.AZURE_CLIENT_ID }} -p ${{ inputs.AZURE_CLIENT_SECRET }} --tenant ${{ inputs.AZURE_TENANT_ID }}
# https://github.com/bacongobbler/azure-blob-storage-upload/issues/21
    - name: upload to azure blob
      shell: bash
        # this was legacy (we used to download artifact after building): az storage blob upload-batch --account-name "stmosaicoprod" --connection-string "${{inputs.CONNECTION_STRING}}" -d '$web' -s "./mosaico-frontend@${{inputs.APP_VERSION}}" 
      run: |
        az storage blob upload-batch --account-name "stmosaicoprod" --connection-string "${{inputs.CONNECTION_STRING}}" -d '$web' -s "./frontend/mosaico-web-ui/frontend-out/" 
        
  
  #we dont add --overwrite because dev somehow uses 2.33.1 AZ CLI which doesnt need --overwrite flag :)

    # - uses: bacongobbler/azure-blob-storage-upload@main
    #   with:
    #     cli_version: 2.34.1
    #     source_dir: "./mosaico-frontend@${{inputs.APP_VERSION}}"
    #     container_name: $web
    #     connection_string: "${{inputs.CONNECTION_STRING}}"
    #     overwrite: 'true'

    # - name: Upload to blob storage
    #   uses: azure/CLI@v1
    #   env:
    #     STORAGE_NAME: sadatastoresearchdev
    #   with:
    #     azcliversion: 2.34.1
    #     inlineScript: |
    #       az storage blob upload-batch --account-name "stmosaicoprod" --connection-string "${{inputs.CONNECTION_STRING}}" -d '$web' -s "./mosaico-frontend@${{inputs.APP_VERSION}}" 